name: ayatdrop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_storage: ^13.2.0
  firebase_messaging: ^16.1.3
  flutter_local_notifications: ^17.1.2
  easy_localization: ^3.0.3
  url_launcher: ^6.2.1
  google_generative_ai: ^0.4.7
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  image_picker: ^1.1.2
  share_plus: ^10.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.2.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.0
  cached_network_image: ^3.4.1
  swipeable_page_route: ^0.4.8
  flutter_dotenv: ^5.1.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/app_icon.png"
  adaptive_icon_background: "#8B2323"
  adaptive_icon_foreground: "images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/translations/
    - assets/users_behavior.json
    - .env
